pipeline {
    agent any

    environment {
        KUBECONFIG_CREDENTIALS = '5274805a-5d4b-43bd-a552-1700d7574ebf' // Your KUBECONFIG credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the latest code from the repo
                git branch: 'main', url: 'https://github.com/sohaib1khan/kubernetes_craft.git'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    withCredentials([file(credentialsId: "${KUBECONFIG_CREDENTIALS}", variable: 'KUBECONFIG')]) {
                        // Using KUBECONFIG from Jenkins credentials
                        sh 'kubectl apply -f Skaffold_Deployments/nginx_app_test/k8s/'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
