pipeline {
    agent any

    environment {
        // Ensure Jenkins has access to the KUBECONFIG credentials stored in Jenkins
        KUBECONFIG_CREDENTIALS = '5274805a-5d4b-43bd-a552-1700d7574ebf' // Replace this with the actual credentials ID from Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the latest code from the repo
                git branch: 'main', url: 'https://github.com/sohaib1khan/kubernetes_craft.git'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Use Kubernetes CLI plugin to run kubectl commands
                    kubernetes.withKubeConfig([credentialsId: "${KUBECONFIG_CREDENTIALS}"]) {
                        sh 'kubectl apply -f Skaffold_Deployments/nginx_app_test/k8s/'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
