pipeline {
    agent any

    environment {
        KUBECONFIG = '/home/devk3s/.kube/config' // Ensure the Jenkins agent has access to your KUBECONFIG
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the latest code from the repo
                git branch: 'main', url: 'https://github.com/sohaib1khan/kubernetes_craft.git'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Apply the Kubernetes manifests from the checked-out repo
                    sh 'kubectl apply -f Skaffold_Deployments/nginx_app_test/k8s/'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
